source 'https://rubygems.org'

#gem 'dm-core'
gem 'sinatra'
gem 'haml'
#gem 'shotgun'
#gem 'sinatra'
gem 'sequel'
gem 'sqlite3'
#gem 'rb-readline'
#gem 'builder'
gem 'json'
gem "rmagick", "~>2.13.2", :require => 'RMagick'
gem 'flickraw'
gem 'prizm'
gem 'thin'
