source 'https://rubygems.org'

gem 'dm-core'
gem 'sinatra'
gem 'haml'
gem 'shotgun'
gem 'warden'
gem 'sinatra'
gem 'sequel'
gem 'sqlite3'
gem 'rb-readline'
gem 'builder'
gem 'json'
gem 'pry'
gem "rmagick", "~>2.13.2", :require => 'RMagick'
gem 'flickraw'
gem 'prizm'
